version: '3'

services:
  mine-node:
    container_name: mine-node
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '6,144M'
        reservations:
          cpus: '0.25'
          memory: '1024M'
    volumes:
      - ./:/app/
    ports:
      - 25565:25565
    working_dir: /app/
    entrypoint: 'npm run start:container'
    links:
      - "mine-db:db"
    networks:
      - mine-network

  mine-db:
    container_name: mine-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - mine-network

networks:
  mine-network:
    driver: bridge
